services:
  # nginx
  web:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php
  app:
    container_name: app
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app

  # mysql

  # redis