services:
  # nginx
  web:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  # php
  app:
    container_name: app
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html
    environment:
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
    networks:
      - app-network

  # redis
  redis-cache:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network


  # mssql

networks:
  app-network:
    driver: "bridge"